spring:
  datasource:
    url: jdbc:h2:mem:demo;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.xiaoxu.rabbitmq_demo.mybatis
security:
  crypto:
    aes-key: "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY="
logging:
  level:
    com.xiaoxu.rabbitmq_demo: INFO
